---
driver:
  name: ec2
  require_chef_omnibus: 12.13.37
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['sg-97e55ef2']
  subnet_id: subnet-a792da8f
  instance_type: t2.small
  tags:
    Env: public
    Type: test

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  client_rb:
    environment: dev

platforms:
  - name: ubuntu-16.04
    driver:
      tags:
        Name: default-aws-ecs-ubuntu-1604

suites:
  - name: default
    run_list:
      - recipe[aws_ecs]
    attributes:
      etc_environment:
        VAULT_ADDR: http://vault.service.dev-us-east-1.consul:8200
        VAULT_TOKEN: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
