language: ruby
rvm:
- 2.2
sudo: required
cache:
  directories:
  - $HOME/.berkshelf
addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk
before_install:
- openssl aes-256-cbc -K $encrypted_47b7ca146a47_key -iv $encrypted_47b7ca146a47_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv .chef ~/.chef
- mv .ssh/travis_ci_ec2.pem ~/.ssh/travis_ci_ec2.pem
- echo 'node_name "trubot"' >> ~/.chef/knife.rb
- echo 'chef_server_url "https://api.opscode.com/organizations/evertrue"' >> ~/.chef/knife.rb
- chmod 600 ~/.chef/knife.rb ~/.chef/encrypted_data_bag_secret
  ~/.ssh/travis_ci_ec2.pem
install:
- eval "$(${CHEF_BIN}/chef shell-init bash)"
- "${CHEF_BIN}/chef gem install kitchen-ec2 coveralls"
before_script:
- "${CHEF_BIN}/berks"
- "${CHEF_BIN}/chef --version"
- "${CHEF_BIN}/rubocop --version"
- "${CHEF_BIN}/foodcritic --version"
script:
- "${CHEF_BIN}/rubocop"
- "${CHEF_BIN}/foodcritic ."
- "${CHEF_BIN}/chef exec rspec --format documentation --color"
- "${CHEF_BIN}/kitchen test -d always -c"
notifications:
  slack:
    secure: luojFHn2IidDB4B1NSmW+D5hbs1WY42ACYO6EPGLk9dBOQTVplIfNqXuonJiLTHzPcs7lQxjR/G4CwFgfxrM2beQoiVftnYeo8/YlQ8YYYNAt1nCe8LqsDeYXdhN8XskgqJ141VeL4nGeegjg0WVJYGnNJU+hb3wU0lqrTr8tu8=
env:
  global:
  - CHEF_BIN=/opt/chefdk/bin
  - EC2_SSH_KEY_PATH="${HOME}/.ssh/travis_ci_ec2.pem"
